// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AppUser struct {
	ID                *string `json:"id,omitempty"`
	Name              string  `json:"name"`
	Username          string  `json:"username"`
	Mobile            string  `json:"mobile"`
	PreferredUsername string  `json:"preferred_username"`
	Role              string  `json:"role"`
	IsActive          bool    `json:"is_active"`
	IsDeleted         bool    `json:"is_deleted"`
	CreatedAt         *int    `json:"created_at,omitempty"`
	UpdatedAt         *int    `json:"updated_at,omitempty"`
}

type AppUserInput struct {
	ID                *string `json:"id,omitempty"`
	Name              string  `json:"name"`
	Username          string  `json:"username"`
	Mobile            string  `json:"mobile"`
	PreferredUsername string  `json:"preferred_username"`
	Role              string  `json:"role"`
	IsActive          *bool   `json:"is_active,omitempty"`
	IsDeleted         *bool   `json:"is_deleted,omitempty"`
}

type AppUserUpdateInput struct {
	ID                *string `json:"id,omitempty"`
	Name              *string `json:"name,omitempty"`
	Username          *string `json:"username,omitempty"`
	Mobile            *string `json:"mobile,omitempty"`
	PreferredUsername *string `json:"preferred_username,omitempty"`
	Role              *string `json:"role,omitempty"`
	IsActive          *bool   `json:"is_active,omitempty"`
	IsDeleted         *bool   `json:"is_deleted,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
